version: '3.8'

services:
  api:
    # image: djinn:test # local image
    image: asia-northeast2-docker.pkg.dev/jinni-api-microservices/master-djinn-test/master:latest # GCP prod instance
    ports:
      - '80:80'
      - '8888:8888'
    env_file: ./.env
    volumes:
      - ./resources/avatars:/resources/avatars
  # ollama:
  #   image: ollama/ollama:latest
  #   volumes:
  #     - ./ollama:/root/.ollama
  #   restart: always
  #   environment:
  #     - MODEL_NAME=llama3  # Specify the model you want to use
  # telemetry:
  #   image: jaegertracing/all-in-one
  #   command:  --collector.otlp.enabled=true
  #   # image: asia-northeast2-docker.pkg.dev/jinni-api-microservices/master-djinn-test/master:latest # GCP prod instance
  #   ports:
  #     - '16686:16686'
  #     - '4317:4317'
  #   env_file: ./.env

# volumes:
  # avatars:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
      # device: data/avatars